title: Yadhunandan KKA
logo: /assets/img/yadhu.png
description: I am a aspiring data scientist who works on implementging different machine learning algorithms for the benefit of the soceity.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
